//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bobine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bobine()
        {
            this.Missions = new HashSet<Missions>();
        }
    
        public int id { get; set; }
        public Nullable<int> floorId { get; set; }
        public decimal @base { get; set; }
        public decimal height { get; set; }
        public decimal depth { get; set; }
        public decimal rotation { get; set; }
        public bool isStanding { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
    
        public virtual Floors Floors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
    }
}
