//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Floors()
        {
            this.Bobine = new HashSet<Bobine>();
            this.Missions = new HashSet<Missions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal p1x { get; set; }
        public decimal p1y { get; set; }
        public decimal p2x { get; set; }
        public decimal p2y { get; set; }
        public decimal p3x { get; set; }
        public decimal p3y { get; set; }
        public decimal p4x { get; set; }
        public decimal p4y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bobine> Bobine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Missions> Missions { get; set; }
    }
}
