//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MulettoApplicationDBEntities : DbContext
    {
        public MulettoApplicationDBEntities()
            : base("name=MulettoApplicationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bobine> Bobine { get; set; }
        public virtual DbSet<BobineEsterne> BobineEsterne { get; set; }
        public virtual DbSet<Floors> Floors { get; set; }
        public virtual DbSet<Missions> Missions { get; set; }
    }
}
